### ISSUE TITLE
prmspy CLI import errors when installing PRMS-Python with python 2

### ISSUE THREAD

**Issue by JohnVolk** [PRMS-Python/PRMS-Python#23]
prmspy works as expected when installing with pip3, I modified the __init__ to have absolute imports to fix an installation bug with pip2 by adding absolute imports as opposed to relative i.e. 

``` python
from prms_python.data import Data
# instead of

from .data import Data
```

This fixed errors when trying to install using pip2. However the prmspy script gives the following errors:

``` bash
$ prmspy 
PRMS-Python/prms_python/__init__.py:19: RuntimeWarning: Parent module 'prms-python' not found while handling absolute import
  from prms_python.data import Data
PRMS-Python/prms_python/__init__.py:20: RuntimeWarning: Parent module 'prms-python' not found while handling absolute import
  from prms_python.optimizer import Optimizer, OptimizationResult
PRMS-Python/prms_python/__init__.py:21: RuntimeWarning: Parent module 'prms-python' not found while handling absolute import
  from prms_python.parameters import Parameters, modify_params
PRMS-Python/prms_python/__init__.py:22: RuntimeWarning: Parent module 'prms-python' not found while handling absolute import
  from prms_python.simulation import Simulation, SimulationSeries
PRMS-Python/prms_python/__init__.py:23: RuntimeWarning: Parent module 'prms-python' not found while handling absolute import
  from prms_python.scenario import Scenario, ScenarioSeries
PRMS-Python/prms_python/__init__.py:24: RuntimeWarning: Parent module 'prms-python' not found while handling absolute import
  from prms_python.util import load_statvar, load_data_file, nash_sutcliffe
Traceback (most recent call last):
  File "/usr/local/bin/prmspy", line 9, in <module>
    load_entry_point('prms-python', 'console_scripts', 'prmspy')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named scripts.prmspy
```

**Comment by JohnVolk** [comment]
From branch 23 I tried: 

``` bash
pip2 install --editable .
```
and now getting this error:

```bash
pip2 install --editable .

Obtaining file:///PRMS-Python
    Complete output from command python setup.py egg_info:
    prms_python/__init__.py:19: RuntimeWarning: Parent module 'prms-python' not found while handling absolute import
      from prms_python.data import Data
    prms_python/__init__.py:20: RuntimeWarning: Parent module 'prms-python' not found while handling absolute import
      from prms_python.optimizer import Optimizer, OptimizationResult
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/PRMS-Python/setup.py", line 1, in <module>
        from prms_python import __version__
      File "prms_python/__init__.py", line 20, in <module>
        from prms_python.optimizer import Optimizer, OptimizationResult
      File "prms_python/optimizer.py", line 17, in <module>
        from .simulation import Simulation, SimulationSeries
      File "prms_python/simulation.py", line 352
    SyntaxError: Non-ASCII character '\xe2' in file prms_python/simulation.py on line 353, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /media/...
```

Any ideas? seems like there is something strange in simulation.py plus it is complaining about the absolute import again.

**Comment by JohnVolk** [comment]
Well it looks like the hyphens I put in to show the file structure in the documentation are causing a problem for Python 2. I installed with pip3 successfully and then tried this from ipython2:

```bash
In [1]: import prms_python
prms_python/__init__.py:19: RuntimeWarning: Parent module 'prms-python' not found while handling absolute import
  from prms_python.data import Data
prms_python/__init__.py:20: RuntimeWarning: Parent module 'prms-python' not found while handling absolute import
  from prms_python.optimizer import Optimizer, OptimizationResult
  File "prms_python/simulation.py", line 353
    │   ├── control
                   ^
SyntaxError: Non-ASCII character '\xe2' in file prms_python/simulation.py on line 354, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by JohnVolk** [comment]
OK, it looks like ``# -*- coding: utf-8 -*-``  needs to be added to the top of scenario.py and simulation.py, and for that matter all module files to avoid these errors in the future...

**Comment by JohnVolk** [comment]
Imports issue are warnings with pip2 install, for example the CLI gives the following warnings

``` bash
$ prmspy 
/PRMS-Python/prms_python/__init__.py:19: RuntimeWarning: Parent module 'prms-python' not found while handling absolute import
  from prms_python.data import Data
/PRMS-Python/prms_python/__init__.py:20: RuntimeWarning: Parent module 'prms-python' not found while handling absolute import
  from prms_python.optimizer import Optimizer, OptimizationResult
/PRMS-Python/prms_python/__init__.py:21: RuntimeWarning: Parent module 'prms-python' not found while handling absolute import
  from prms_python.parameters import Parameters, modify_params
/PRMS-Python/prms_python/__init__.py:22: RuntimeWarning: Parent module 'prms-python' not found while handling absolute import
  from prms_python.simulation import Simulation, SimulationSeries
/PRMS-Python/prms_python/__init__.py:23: RuntimeWarning: Parent module 'prms-python' not found while handling absolute import
  from prms_python.scenario import Scenario, ScenarioSeries
/PRMS-Python/prms_python/__init__.py:24: RuntimeWarning: Parent module 'prms-python' not found while handling absolute import
  from prms_python.util import load_statvar, load_data_file, nash_sutcliffe
Usage: prmspy [OPTIONS] COMMAND [ARGS]...

  access PRMS-Python functionality from the command line

Options:
  --help  Show this message and exit.

Commands:
  nash_sutcliffe_matrix  Save a PDF of the Nash-Sutcliffe created from...
  param_scale_sim        Provide params and scaling values; run PRMS...
```

So clearly the problem was the parent module was named ``prms-python`` in setup.py and as the name in __init__.py. I changed those to ``prms_python`` and the import warnings go away. The only issue is that the name of the module is PRMS-Python, and we refer to it as prms-python in other places... I think the fix that is working for me now is to change name in __init__.py to ``__name__ = 'prms_python' `` and leave the name in setup.py as prms-python. I hope this won't cause an error when installing from PyPI as pip install prms-python. Do you know if this inconsistency will cause any errors? It works for me with pip2 install --editable .
